---
# Location where configuration files will be stored.
config_dir: '~/docker/'
home_dir: '/home/matt'

ts_authkey: 'auth'

# Pi-hole configuration.
pihole_hostname: server
my_timezone: America/Los_Angeles
pihole_password: "password"

nextcloud_location: ~/nextcloud
nextcloud_db_root_password: "password"
nextcloud_db_password: "password"
nextcloud_db_name: "nextcloud"
nextcloud_db_user: "nextcloud"

drives:
  - { path: "{{ home_dir }}/media",      uuid: "" }
  - { path: "{{ home_dir }}/nextcloud",  uuid: "" }
  - { path: "{{ home_dir }}/data",       uuid: "" }
  - { path: "{{ home_dir }}/docker",     uuid: "" }

docker_services:
  #  - { name: "actual-budget",    template: "templates/actual-budget-docker-compose.yml.j2",    tailscale_enable: true  }
  #  - { name: "freshrss",         template: "templates/freshrss-docker-compose.yml.j2",         tailscale_enable: true  }
  - { name: "home-assistant",   template: "templates/home-assistant-docker-compose.yml.j2",   tailscale_enable: true  }
  - { name: "metube",           template: "templates/metube-docker-compose.yml.j2",           tailscale_enable: true  }
  - { name: "nextcloud",        template: "templates/nextcloud-docker-compose.yml.j2",        tailscale_enable: true  }
  #  - { name: "pihole", template: "templates/pi-hole-docker-compose.yml.j2", tailscale_enable: false }
  - { name: "jellyfin",         template: "templates/jellyfin-docker-compose.yml.j2",         tailscale_enable: true  }
  - { name: "jellyfinp",        template: "templates/jellyfinp-docker-compose.yml.j2",        tailscale_enable: true  }
