# Location where configuration files will be stored.
home_dir:       '/home/matt'
timezone:       'America/Los_Angeles'
puid:           '1000'
pgid:           '1000'
jellyfin_puid:  '1001'
jellyfin_pgid:  '1001'

tailscale_dir:  '{{ home_dir }}/tailscale'

vpn_provider: ''
openvpn_user: ''
openvpn_password: ''
vpn_region: ''

calibre_username: ''
calibre_password: ''
calibre_args: ''

media_dir:      '{{ home_dir }}/media'
nextcloud_dir:  '{{ home_dir }}/nextcloud'
data_dir:       '{{ home_dir }}/data'
docker_dir:     '{{ home_dir }}/docker'

music_dir:      '{{ media_dir }}/audio/music'
audio_dir:      '{{ media_dir }}/audio'
books_dir:      '{{ media_dir }}/books'
movies_dir:     '{{ media_dir }}/movies'
tv_dir:         '{{ media_dir }}/tv'
youtube_dir:    '{{ media_dir }}/youtube'
downloads_dir:  '{{ media_dir }}/downloads'

drives:
  - { path: "{{ media_dir }}",      uuid: "" }
  - { path: "{{ nextcloud_dir }}",  uuid: "" }
  - { path: "{{ data_dir }}",       uuid: "" }
  - { path: "{{ docker_dir }}",     uuid: "" }

ts_authkey: ''

nextcloud_db_root_password: "password"
nextcloud_db_password: "password"
nextcloud_db_name: "nextcloud"
nextcloud_db_user: "nextcloud"

docker_services:
  #  - { name: "actual-budget",    template: "templates/actual-budget-docker-compose.yml.j2",    tailscale_enable: true  }
  #  - { name: "freshrss",         template: "templates/freshrss-docker-compose.yml.j2",         tailscale_enable: true  }
  - { name: "home-assistant",   template: "templates/home-assistant-docker-compose.yml.j2",   tailscale_enable: true  }
  - { name: "metube",           template: "templates/metube-docker-compose.yml.j2",           tailscale_enable: true  }
  - { name: "nextcloud",        template: "templates/nextcloud-docker-compose.yml.j2",        tailscale_enable: true  }
  #  - { name: "pihole", template: "templates/pi-hole-docker-compose.yml.j2", tailscale_enable: false }
  - { name: "jellyfin",         template: "templates/jellyfin-docker-compose.yml.j2",         tailscale_enable: true  }
  - { name: "jellyfinp",        template: "templates/jellyfinp-docker-compose.yml.j2",        tailscale_enable: true  }
  - { name: "arr",        template: "templates/arr-docker-compose.yml.j2",        tailscale_enable: true  }
  - { name: "calibre",    template: "templates/calibre-docker-compose.yml.j2",  tailscale_enable: false }
