---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Add Debian backports GPG keys
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "{{ item }}"
  loop:
    - 04EE7237B7D453EC
    - 648ACFD622F3D138
    - 0E98404D386FA1D9
    - 6ED0E7B82643E131

- name: Add Buster backports repo
  ansible.builtin.apt_repository:
    repo: "deb http://httpredir.debian.org/debian buster-backports main contrib non-free"
    state: present
    filename: debian-backports

- name: Install libseccomp2 from backports
  ansible.builtin.apt:
    name: libseccomp2
    state: latest
    default_release: buster-backports

- name: Debian libseccomp fix for 32-bit
  ansible.builtin.import_tasks: tasks/debian_libseccomp_fix.yml
  when:
    - ansible_facts.os_family == "Debian"
    - ansible_facts.userspace_bits == "32"
    - ansible_facts.packages['libseccomp2'][0]['version'] is version('2.4.4', '<')
