---
- name: Check if Docker is installed
  ansible.builtin.command: which docker
  register: docker_command_result
  changed_when: false
  failed_when: false

- name: Download Docker convenience script if missing
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: '0775'
  when: docker_command_result.rc != 0

- name: Run Docker convenience script if Docker not installed
  ansible.builtin.command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: docker_command_result.rc != 0

- name: Ensure Docker is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Install Debian dependencies
  ansible.builtin.apt:
    name:
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3-pip
      - git
      - rsync
      - docker-compose-plugin
      - resolvconf
    state: present
    update_cache: true
  when: ansible_facts.os_family == "Debian"

- name: Install Archlinux dependencies
  community.general.pacman:
    name:
      - libffi
      - openssl
      - base-devel
      - python-pip
      - git
      - rsync
      - docker-compose-plugin
    state: present
    update_cache: true
  when: ansible_facts.os_family == "Archlinux"

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Reset connection so docker group is picked up
  meta: reset_connection

